### ISSUE TITLE
Import issue: ModuleNotFoundError: No module named 'droid_backends'

### ISSUE THREAD

**Issue by liuyq055** [Jianxff/droid_metric#11]
I have followed the installation instructions provided in the repository, and I am not sure what might be causing this issue.
Could you please advise on how to resolve this issue? Is there any additional setup or installation step that I might have missed?

**Comment by Jianxff** [comment]
Hi,
The problem seems from wrong installation for DROID-SLAM. You can check the following:
- Whether the repo was cloned correctly. Pay attetion to the `recursive cloning`
- Whether the DROID-SLAM was installed successfully. You might check the logs from the console. Maybe some other modules cause the error.
- 
You can copy and upload the whole installation logs from the console if the error still exists.

**Comment by liuyq055** [comment]
Thank you for your excellent work. Following your advice, I successfully ran the code and validated it on the ADVIO-Seq15 dataset. However, the results were not as expected. I have confirmed that the depth map is correct, but I'm wondering why the performance is still suboptimal. Could you provide any insights?
![image](https://github.com/user-attachments/assets/625413da-c8a2-4dd3-9054-154384b300f6)

**Comment by Jianxff** [comment]
Hi,

Sorry for that, I have no idea for the problem by now. You can check if all data for input is correct including intrinsics and console args. 

You can copy your execution command so that I can get more infomation.

BTW, the GT data structure for ADVIO is a little bit strange, you may have to look into the coordinate for the GT pose and the quarternion format for Rotation data.

**Comment by liuyq055** [comment]
Thank you for your reply, my execution command is mainly:
python depth.py --rgb data/advio-15/iphone/frames --intr data/advio-15/iphone/intrinsics.txt 
 python run.py --rgb data/advio-15/iphone/frames --depth depth --intr data/advio-15/iphone/intrinsics.txt --save_poses poses
python mesh.py --rgb data/advio-15/iphone/frames --depth depth --poses poses/ --intr data/advio-15/iphone/intrinsics.txt --save mesh/ply

Described in your readme ## droid-slam
python run.py --rgb $/path/to/rgb/dir --depth $/path/to/depth/dir --intr $/path/to/intrinsic/file --viz
# for more options, check `run.py`. You should run depth estimation first. This command only saves the raw_trajectory , it doesn't convert it to a pose, so I looked at the code and added a new save path for save_poses.
Thank you very much for your reply.

**Comment by Jianxff** [comment]
That's strange, it's not supposed to be like this.

Have you ever check `mesh_raw.ply` ? The unsimplified mesh will be saved under the same dir of input args `--save`. I'm not sure if it is caused by RGBD fusion or mesh simplify.

**Comment by liuyq055** [comment]
Sorry for the delayed reply, I finished my opening report a while ago and went. As you suggested I checked the mesh file and the results are still poor. I haven't found what the problem is yet, thinking if there is something wrong with the saved pose? Do you have any suggestions?
![2024-09-25_19-25](https://github.com/user-attachments/assets/e4f38f1b-151d-4e03-bf6f-17c0cb8fd2d5)

**Comment by Jianxff** [comment]
Hi,
I have re-tested the seq on my machine, everything works well.

Something may be wrong with the intrinsic file, which supports only 4 elements arranged in `fx, fy, cx, cy`. Please check it. The following is the intrinsic file for seq15:

```
1082.4
1084.4
364.68
643.31
```

I haven't found other possible problems. So if you're still having trouble, I can upload the poses file as a reference.

Here are my commands:

```
python depth.py --rgb ../seq15/rgb/ --intr ../seq15/calib.txt --out ../seq15/depth
python run.py --rgb ../seq15/rgb/ --depth ../seq15/depth/ --intr ../seq15/calib.txt --save_poses ../seq15/poses --viz --viz-save ../seq15/viz
python mesh.py --rgb ../seq15/rgb/ --depth ../seq15/depth/ --intr ../seq15/calib.txt --poses ../seq15/poses/ --save ../seq15/mesh.ply
```

**Comment by liuyq055** [comment]
I have tested again according to the command you provided and checked the intrinsics file. There are no errors displayed in depth.py and run.py, but the results in mesh.py are still not satisfactory, and I don't know where the problem lies.
If it's convenient for you, could you please upload the poses file generated in the second step for my reference? Thank you very much.

**Comment by Jianxff** [comment]
[poses.zip](https://github.com/user-attachments/files/17145770/poses.zip)

That's it.

**Comment by liuyq055** [comment]
Additionally, I was wondering if it would be convenient for you to share the mesh file generated in the third step for my reference. Thank you very much for your excellent work.

**Comment by Jianxff** [comment]
[mesh_raw.zip](https://github.com/user-attachments/files/17146116/mesh_raw.zip)

This is the file of the raw mesh without simplification. I have no idea what's happening. You may compare your code about mesh generation with the latest on the repo.

**Comment by liuyq055** [comment]
I have re-downloaded the latest repo, and it worked!! Thank you so much!!

**Comment by Jianxff** [comment]
Good to hear that.
