### ISSUE TITLE
Question related to volume estimation

### ISSUE THREAD

**Issue by Nacriema** [Jianxff/droid_metric#14]
Hi, thank you for your amazing work! I have a question: 
Can we perform object's volume estimation directly from the generated mesh? I see that the `Metric3Dv2` model that can allow us to measure distances. Thank you in advanced.

**Comment by Jianxff** [comment]
Hi，
It is possible to estimate the volume of objects as the volume size is real, just as that in Metric3D. But you'll need to design an algorithm to perform estimation. Pay attention that the final output results are surface-reconstruction.

**Comment by Nacriema** [comment]
Yes, I understand. I appreciate how quickly you responded!
