### ISSUE TITLE
is the slam.py also refine the depth as like droid paper?

### ISSUE THREAD

**Issue by Gorokee** [Jianxff/droid_metric#16]
The original droid paper jointly refine the poses and depths.
I just wondered if slam.py also jointly refines the initial depth map (estimated from metric3D).

If not, could you share any idea to refine the initial depth and save them (for better 3D mesh reconstruction afterwards)?

Thanks,

**Comment by Jianxff** [comment]
Hi,
As I known, Droid-SLAM will automatically refine poses and depths jointly if the depths are available. `slam.py` does not modify the original processing, so it will jointly refine the naive depth map.

You can refer to [depth_video.py](https://github.com/princeton-vl/DROID-SLAM/blob/main/droid_slam/depth_video.py) and [droid_kernels.cu](https://github.com/princeton-vl/DROID-SLAM/blob/main/src/droid_kernels.cu) of the original Droid-SLAM repo for more details about the jointly refine.

**Comment by Gorokee** [comment]
Hi,

thanks for the prompt answer!

I see, then for pose estimation it uses the refined depth.

But it seems the mesh.py is using the initial depth (from Metric3D) for meshing,,
If so, may I ask for your guide to use the refined depth for the mesh.p step (which could improve the 3D reconstruction results)?

Thanks,

**Comment by Jianxff** [comment]
Sorry for late reply,

You're right that `mesh.py` use the naive depth as I hadn't taken that aspect into account. Looks forward to your further experiments!

To save the refined depth, you can follow [`save_reconstruction`](https://github.com/princeton-vl/DROID-SLAM/blob/8016d2b9b72b101a3e9ac804ebf20b4c654dc291/demo.py#L75), in which the `disp_up` refers to the upsampled depth maps and saved as one numpy file. [`depth_video.py`](https://github.com/princeton-vl/DROID-SLAM/blob/main/droid_slam/depth_video.py) provides more details about the operation for depth maps.

**Comment by Gorokee** [comment]
Hi Jianxff,

I see, thanks for the guidance and reply!! That was really helpful!

Best,

**Comment by Gorokee** [comment]
Hi Jianxff,

thanks for suggesting the way to save the refined depth.

In the RGB-D mode of the slam, however, the output refined depth after the bundle adjustment just returns "zero" value.

I was wondering if you could provide any hint for that.

Do you think it is correct phenomena?
Is it because RGB-D mode does not refine the initial depth map and fully rely on the initial depth map?

Thanks!

**Comment by jin-cao-tma** [comment]
> In the RGB-D mode of the slam, however, the output refined depth after the bundle adjustment just returns "zero" value.

Hi, I also meet this problem, do you have any method to solve it?
