### ISSUE TITLE
RuntimeError: Failed to find function: mono.model.backbones.vit_giant2_reg

### ISSUE THREAD

**Issue by qsisi** [Jianxff/droid_metric#17]
![image](https://github.com/user-attachments/assets/121a1867-ea77-4a47-ac47-c7aac9dcbc2b)

**Comment by Jianxff** [comment]
Hi，
It looks like that the Metric3D module was not cloned correctly.
Try `git clone https://github.com/Jianxff/droid_metric.git --recursive` or `git submodule update --init --recursive`

**Comment by qsisi** [comment]
I did clone this repo recursively, and it appears that this line causes the error:
![image](https://github.com/user-attachments/assets/58dd6795-4620-44e1-af2a-8827f7432adf)

**Comment by Jianxff** [comment]
Metric3D module is from its official repo, which shouldn't go wrong.
I have add the metric3d path to syspath at [this line](https://github.com/Jianxff/droid_metric/blob/b75134dd0145d62078328c850080e5e97a388c6f/modules/metric.py#L14) so that the `mono` module can be found. 

Maybe you can provide the whole input and output for a further debuging.

**Comment by qsisi** [comment]
The issue is caused by not installing timm, after installing timm, the problem is solved.

**Comment by Alan-zhong** [comment]
@qsisi 
hi，i have installed timm， but also have the same problem
droid_metric) alan@alan-System-Product-Name:~/droid_metric$ conda list
# packages in environment at /home/alan/anaconda3/envs/droid_metric:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   2.2.2                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
argcomplete               3.6.2                    pypi_0    pypi
asttokens                 3.0.0                    pypi_0    pypi
attrs                     25.3.0                   pypi_0    pypi
beautifulsoup4            4.13.4                   pypi_0    pypi
blas                      1.0                         mkl  
blinker                   1.9.0                    pypi_0    pypi
brotli-python             1.0.9            py39h6a678d5_9  
bzip2                     1.0.8                h5eee18b_6  
ca-certificates           2025.2.25            h06a4308_0  
certifi                   2025.4.26        py39h06a4308_0  
chardet                   5.2.0                    pypi_0    pypi
charset-normalizer        3.4.2                    pypi_0    pypi
click                     8.1.8                    pypi_0    pypi
cmake                     4.0.2                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
comm                      0.2.2                    pypi_0    pypi
configargparse            1.7                      pypi_0    pypi
contourpy                 1.3.0                    pypi_0    pypi
cuda-cudart               11.8.89                       0    nvidia
cuda-cupti                11.8.87                       0    nvidia
cuda-libraries            11.8.0                        0    nvidia
cuda-nvrtc                11.8.89                       0    nvidia
cuda-nvtx                 11.8.86                       0    nvidia
cuda-runtime              11.8.0                        0    nvidia
cuda-version              12.9                          3    nvidia
cycler                    0.12.1                   pypi_0    pypi
dash                      3.0.4                    pypi_0    pypi
decorator                 5.2.1                    pypi_0    pypi
dominate                  2.9.1                    pypi_0    pypi
droid-backends            0.0.0                    pypi_0    pypi
evo                       1.31.1                   pypi_0    pypi
exceptiongroup            1.3.0                    pypi_0    pypi
executing                 2.2.0                    pypi_0    pypi
fastjsonschema            2.21.1                   pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.18.0                   pypi_0    pypi
flask                     3.0.3                    pypi_0    pypi
fonttools                 4.58.0                   pypi_0    pypi
freetype                  2.13.3               h4a9f257_0  
fsspec                    2025.3.2                 pypi_0    pypi
gdown                     5.2.0                    pypi_0    pypi
gmp                       6.3.0                h6a678d5_0  
gmpy2                     2.2.1            py39h5eee18b_0  
gnutls                    3.6.15               he1e5248_0  
grpcio                    1.71.0                   pypi_0    pypi
html4vision               0.5.0                    pypi_0    pypi
huggingface-hub           0.31.2                   pypi_0    pypi
idna                      3.10                     pypi_0    pypi
importlib-metadata        8.7.0                    pypi_0    pypi
importlib-resources       6.5.2                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46306  
ipython                   8.18.1                   pypi_0    pypi
ipywidgets                8.1.7                    pypi_0    pypi
itsdangerous              2.2.0                    pypi_0    pypi
jedi                      0.19.2                   pypi_0    pypi
jinja2                    3.1.6            py39h06a4308_0  
joblib                    1.5.0                    pypi_0    pypi
jpeg                      9e                   h5eee18b_3  
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2025.4.1                 pypi_0    pypi
jupyter-core              5.7.2                    pypi_0    pypi
jupyterlab-widgets        3.0.15                   pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
lame                      3.100                h7b6447c_0  
lcms2                     2.16                 h92b89f2_1  
ld_impl_linux-64          2.40                 h12ee557_0  
lerc                      4.0.0                h6a678d5_0  
libcublas                 11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufile                 1.14.0.30                     4    nvidia
libcurand                 10.3.10.19                    0    nvidia
libcusolver               11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libdeflate                1.22                 h5eee18b_0  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h5eee18b_3  
libidn2                   2.3.4                h5eee18b_0  
libnpp                    11.8.0.86                     0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.7.0                hde9077f_0  
libunistring              0.9.10               h27cfd23_0  
libwebp-base              1.3.2                h5eee18b_1  
lietorch                  0.2                      pypi_0    pypi
lit                       18.1.8                   pypi_0    pypi
lz4                       4.4.4                    pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_1  
markdown                  3.8                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                3.0.2            py39h5eee18b_0  
matplotlib                3.9.4                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.1.0         h213fc3f_46344  
mkl-service               2.4.0            py39h5eee18b_2  
mkl_fft                   1.3.11           py39h5eee18b_0  
mkl_random                1.2.8            py39h1128e8f_0  
mmcv                      2.2.0                    pypi_0    pypi
mmengine                  0.10.7                   pypi_0    pypi
mpc                       1.3.1                h5eee18b_0  
mpfr                      4.2.1                h5eee18b_0  
mpmath                    1.3.0            py39h06a4308_0  
narwhals                  1.39.0                   pypi_0    pypi
natsort                   8.4.0                    pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.6.0                    pypi_0    pypi
nettle                    3.7.3                hbbd107a_1  
networkx                  3.2.1            py39h06a4308_0  
numexpr                   2.10.2                   pypi_0    pypi
numpy                     1.26.1                   pypi_0    pypi
numpy-base                2.0.1            py39hb5e798b_1  
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
open3d                    0.19.0                   pypi_0    pypi
opencv-python             4.11.0.86                pypi_0    pypi
openh264                  2.1.1                h4ff587b_0  
openjpeg                  2.5.2                h0d4d230_1  
openssl                   3.0.16               h5eee18b_0  
packaging                 25.0                     pypi_0    pypi
pandas                    2.2.3                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
pillow                    11.2.1                   pypi_0    pypi
pip                       25.1               pyhc872135_2  
platformdirs              4.3.8                    pypi_0    pypi
plotly                    6.0.1                    pypi_0    pypi
plyfile                   1.1                      pypi_0    pypi
prompt-toolkit            3.0.51                   pypi_0    pypi
protobuf                  6.30.2                   pypi_0    pypi
psutil                    7.0.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.3                    pypi_0    pypi
py3-wget                  1.0.12                   pypi_0    pypi
pygments                  2.19.1                   pypi_0    pypi
pyparsing                 3.2.3                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.21               he870216_1  
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch-cuda              11.8                 h7e8668a_6    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2025.2                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
referencing               0.36.2                   pypi_0    pypi
requests                  2.32.3           py39h06a4308_1  
retrying                  1.3.4                    pypi_0    pypi
rich                      14.0.0                   pypi_0    pypi
rosbags                   0.9.23                   pypi_0    pypi
rpds-py                   0.24.0                   pypi_0    pypi
ruamel-yaml               0.18.10                  pypi_0    pypi
ruamel-yaml-clib          0.2.12                   pypi_0    pypi
safetensors               0.5.3                    pypi_0    pypi
scikit-learn              1.6.1                    pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
setuptools                78.1.1           py39h06a4308_0  
six                       1.17.0                   pypi_0    pypi
soupsieve                 2.7                      pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
stack-data                0.6.3                    pypi_0    pypi
sympy                     1.14.0                   pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0  
tensorboard               2.19.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
termcolor                 3.1.0                    pypi_0    pypi
threadpoolctl             3.6.0                    pypi_0    pypi
timm                      1.0.15                   pypi_0    pypi
tk                        8.6.14               h39e8969_0  
tomli                     2.2.1                    pypi_0    pypi
torch                     2.0.1+cu117              pypi_0    pypi
torch-scatter             2.1.2+pt20cu117          pypi_0    pypi
torchaudio                2.0.2                    pypi_0    pypi
torchtriton               2.0.0                      py39    pytorch
torchvision               0.15.2                   pypi_0    pypi
tqdm                      4.67.1                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
typing-extensions         4.13.2                   pypi_0    pypi
typing_extensions         4.12.2           py39h06a4308_0  
tzdata                    2025.2                   pypi_0    pypi
urllib3                   2.4.0                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
werkzeug                  3.0.6                    pypi_0    pypi
wheel                     0.45.1           py39h06a4308_0  
widgetsnbextension        4.0.14                   pypi_0    pypi
xformers                  0.0.21                   pypi_0    pypi
xz                        5.6.4                h5eee18b_1  
yapf                      0.43.0                   pypi_0    pypi
zipp                      3.21.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1  
zstandard                 0.23.0                   pypi_0    pypi
zstd                      1.5.6                hc292b87_0
