### ISSUE TITLE
Issue with StereoCalibrationWizard repository

### ISSUE THREAD

**Issue by cvicenro7** [Jianxff/droid_metric#3]
Hi, I have a question related to your StereoCalibrationWizard repository (https://github.com/Jianxff/StereoCalibrationWizard). However, since the repository is read-only it doesn't allow for new issues to be open, so I thought I'd do it here.

I was wondering if you could provide some installation and usage guidelines. So far, when I try to run it I can open the Wizard GUI but when I click on the Calibrate button (with init mode) nothing happens (the camera doesn't open). Is it because at the moment I also have one camera connected? Also, how do the other calibration modes "free" and "input" work?

I'm looking forward to your response. Thank you very much!
![stereocalwizard](https://github.com/Jianxff/droid_metric/assets/63311668/3276af31-097e-4564-a2a2-db19a99e0cb3)

**Comment by Jianxff** [comment]
Refer to the console logs, maybe the config file is not loaded or set correctly. Check `config.xml`, the camera index should be pre-set there.

But I'm sorry I haven't focus on that project for a long time, it's just a backup when experiment. I can't provide further help cuz I have no time review the project by now.

Anyway, that project is a little out of date and complex. Guiding for the next pose of chessboard is not necessary and get quite little improvement. A simple mono camera calibration script by opencv-python can be found on [part of](https://github.com/Jianxff/droid_metric/blob/main/modules/utils.py) this repo, and if you want to learn about stereo calibration, [this video](https://www.youtube.com/watch?v=yKypaVl6qQo) may be a good help.

Best,

**Comment by cvicenro7** [comment]
Thank you very much for the fast reply! I managed to get it working. However, now I'm trying to use calibration input images instead of images from cameras connected to my device. I haven't achieved it yet so far. For this calibration mode, do you manually have to include the images in the data/images folder and change the data/images/count.txt to the number of images used? I'm also setting the camera index to -1 to indicate the images are imported from files.

I understand you do not review this project anymore, but is there any help you could provide in this regard?

I understand that the pose guidance only leads to a little improvement, but in my project it would be quite necessary since I am trying to automatize a camera calibration protocol, thus the selection of poses could reduce the performance bias among users.

**Comment by cvicenro7** [comment]
Thank you for the fast reply! I got it up and running, and I can finally use it. Thank you again:)

**Comment by Jianxff** [comment]
Glad to hear that. The core algorithm of guidance is modified above the [monocular guidance system](https://github.com/pengsongyou/CalibrationWizard), you can check the paper for basic principles.
