### ISSUE TITLE
Eigen link is dead

### ISSUE THREAD

**Issue by Asylbeck** [Jianxff/droid_metric#7]
the link in thirdparty eigen folder is dead and therefore doesn't clone the submodule - which fails the build

**Comment by Jianxff** [comment]
Hello, it looks like the error is from the original DROID-SLAM repo, which I cannot fix. You can try to download the latest Eigen  from: https://eigen.tuxfamily.org/index.php?title=Main_Page, and place the folder at where eigen module should be.

**Comment by Asylbeck** [comment]
understood, can you specify which specific "Metric3d" commit should be used with your code - so that we can avoid such problems? I created another issue that might be related to Metric3D cuda/torch version mismatch with installation steps.

**Comment by Jianxff** [comment]
Hi, 

I use the latest Metric3D and it seems that the code is not changed by now. Specific CUDA/Torch version is not necessary, you can change them by yourself.
