### ISSUE TITLE
Can the point cloud generated by mesh.py be adjusted

### ISSUE THREAD

**Issue by bankxi** [Jianxff/droid_metric#9]
Hello, thank you for providing a very good project. I would like to ask if when I use mesh.py, the generated ply file only retains point cloud data for one lane, but my image includes roadside guardrails and signs. Can I adjust any parameters to display the surrounding environment of the lane on the point cloud map as well.

**my images:**
![img_v3_02ck_a1c8f464-96e7-405c-b16d-2cf050ebf71g](https://github.com/Jianxff/droid_metric/assets/53323046/c2598710-708b-44e0-a537-b1fa669bbf3b)

**points cloud:**
![img_v3_02ck_187fb427-a401-46f0-bc4c-2d429d31e21g](https://github.com/Jianxff/droid_metric/assets/53323046/7c6c840c-8b95-4a77-9ce9-ac61edda5b59)

**Comment by Jianxff** [comment]
Hi, I think that if the trajectory is correct, you can check the [fusion function](https://github.com/Jianxff/droid_metric/blob/2acd8f95f8f946ff08a0580e00271fca6c4a6cc5/modules/fusion.py#L14). The parameter  `depth_trunc` may truncate depth values that out of threshold. 

You can add this param on the [RGBD Fusion Pipeline](https://github.com/Jianxff/droid_metric/blob/2acd8f95f8f946ff08a0580e00271fca6c4a6cc5/mesh.py#L28) and increase the default value. The default value was set for indoor scenes, so it can be a little bit of small (only 5 meters). You can adjust it to fit outdoor scenes better, such as 15 meters or larger.

Btw, increasing the truncated value will also increase computation. So the trunc value should not be too large.

**Comment by bankxi** [comment]
Thank you very much. My problem has been resolved. By the way, this project is great!
![image](https://github.com/Jianxff/droid_metric/assets/53323046/98b7c6ab-3393-47f0-ab21-e840385888d2)
